### ISSUE TITLE
gluufederation/config-init:3.1.1_dev have problem generation configuration

### ISSUE THREAD

**Issue by doughuang168** [GluuFederation/k8s-gluu-server#2]
I follow the README instruction start minikube in windows 10 environment and execute following:

kubectl create -f stage1.yaml
minikube ip
kubectl get svc

However, I have problem generation configuration. The README dones not specify where to perfomr "docker run ...", So, I ssh into minikube to execute it.
Here is the what happen inside minukube:

$ ping 192.168.137.196
PING 192.168.137.196 (192.168.137.196): 56 data bytes
64 bytes from 192.168.137.196: seq=0 ttl=64 time=0.034 ms
64 bytes from 192.168.137.196: seq=1 ttl=64 time=0.120 ms
64 bytes from 192.168.137.196: seq=2 ttl=64 time=0.122 ms
^C
--- 192.168.137.196 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.034/0.092/0.122 ms
$ docker run --rm \
>     gluufederation/config-init:3.1.1_dev \
>     --admin-pw admin@1234 \
>     --email support@gluu.local \
>     --domain k8s-gluu-server \
>     --org-name k8s-gluu-server \
>     --kv-host 192.168.137.196 \
>     --kv-port 31399 \
>     --save
        Unable to find image 'gluufederation/config-init:3.1.1_dev' locally
3.1.1_dev: Pulling from gluufederation/config-init
8387d9ff0016: Pull complete
3b52deaaf0ed: Pull complete
4bd501fad6de: Pull complete
a3ed95caeb02: Pull complete
2fe4faf9c7e4: Pull complete
6fbd5ca95fe8: Pull complete
9f645e9b5ab6: Pull complete
cdeaf6c751bb: Pull complete
015a8cbf7db7: Pull complete
99e410244f88: Pull complete
05db079cb274: Pull complete
51151677d612: Pull complete
90aa4c24edd6: Pull complete
e794ba4f3b2b: Pull complete
Digest: sha256:ac22484ec9b7249f4f5d4fc4236e31b2fe432ed510cbf18b76065cb2d072a470
Status: Downloaded newer image for gluufederation/config-init:3.1.1_dev
Traceback (most recent call last):
  File "./entrypoint.py", line 475, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./entrypoint.py", line 468, in main
    consul.kv.set(k, v)
  File "/usr/local/lib/python2.7/dist-packages/consulate/api/kv.py", line 259, in set
    return self.__setitem__(item, value)
  File "/usr/local/lib/python2.7/dist-packages/consulate/api/kv.py", line 92, in __setitem__
    self._set_item(item, value)
  File "/usr/local/lib/python2.7/dist-packages/consulate/api/kv.py", line 389, in _set_item
    'Error setting "{0}" ({1})'.format(item, response.status_code))
KeyError: 'Error setting "encoded_salt" (500)'
$

Please advise how to resolve the issue.

**Comment by mzico** [comment]
For any kind of support related issue, please use our support portal: https://support.gluu.org
